export const FontFamilies = {
  bartleenScript: 'Bartleen Script',
  latoBoldItalic: 'Lato Bold Italic',
  latoBlackItalic: 'Lato Black Italic',
  latoBlack: 'Lato Black',
  latoBold: 'Lato Bold',
  latoHairlineItalic: 'Lato Hairline Italic',
  latoHairline: 'Lato Hairline',
  latoHeavyItalic: 'Lato Heavy Italic',
  latoHeavy: 'Lato Heavy',
  latoItalic: 'Lato Italic',
  latoLightItalic: 'Lato Light Italic',
  latoLight: 'Lato Ligth',
  latoMediumItalic: 'Lato Medium Italic',
  latoMedium: 'Lato Medium',
  latoRegular: 'Lato Regular',
  latoSemiboldItalic: 'Lato Semibold Italic',
  latoSemibold: 'Lato Semibold',
  latoThinItalic: 'Lato Thin Italic',
  latoThin: 'Lato Thin',
};
